name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build sender
      run: g++ -Wall -Wextra -Werror --coverage  -o Sender sender/*.cpp
      
    - name: build receiver
      run: g++ -Wall -Wextra -Werror --coverage  -o Receiver receiver/*.cpp
      
    - name: static analysis
      run: cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 .
      
    - name: pipelining
      run: ./Sender|./Receiver
      
    - name: build receiver-test
      run: g++ -Wall -Wextra --coverage -o receiver-test receiver-test/receiver-test.cpp receiver/receiver.cpp
      
    - name: coverage report sender
      run: gcov -r sender.cpp
      
    - name: coverage report receiver
      run: gcov -r receiver.cpp

